# Generated by Django 4.1.4 on 2022-12-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0002_computer_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="computermodel",
            name="computer_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="makes",
                to="equip.make",
            ),
        ),
    ]
