# Generated by Django 4.1.4 on 2022-12-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0003_make_alter_computermodel_computer_model"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Computer",
            new_name="Equipment",
        ),
        migrations.RenameModel(
            old_name="ComputerModel",
            new_name="EquipmentModel",
        ),
        migrations.RenameField(
            model_name="maintenance",
            old_name="computer",
            new_name="equipment",
        ),
    ]
