# Generated by Django 4.1.4 on 2022-12-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0005_alter_equipment_options_alter_equipmentmodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equip_type", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="equip_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_types",
                to="equip.equipmenttype",
            ),
        ),
    ]
