# Generated by Django 4.1.4 on 2022-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0007_alter_maintenance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="branch",
            field=models.CharField(default="head office", max_length=100),
        ),
    ]
