# Generated by Django 4.1.4 on 2022-12-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0009_remove_maintenance_comment_maintenancecomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_notes",
                        to="equip.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.RemoveField(
            model_name="maintenancecomment",
            name="equip_maintenance",
        ),
        migrations.DeleteModel(
            name="Maintenance",
        ),
        migrations.DeleteModel(
            name="MaintenanceComment",
        ),
    ]
