# Generated by Django 4.1.4 on 2022-12-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0010_equipmentnote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentnote",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
