# Generated by Django 4.1.4 on 2022-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equip", "0011_equipmentnote_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentnote",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="file"
            ),
        ),
    ]
